<?php

/**
 * @file
 * Handles installation for RajaOngkir module.
 */

/**
 * Implements hook_uninstall().
 */
function commerce_rajaongkir_uninstall() {
  $items = array(
    'commerce_rajaongkir_account_type',
    'commerce_rajaongkir_administrative_area',
    'commerce_rajaongkir_api_key',
    'commerce_rajaongkir_courier',
    'commerce_rajaongkir_dependent_locality',
    'commerce_rajaongkir_locality',
    'commerce_rajaongkir_rates_dependent_locality',
    'commerce_rajaongkir_rates_timeout',
  );
  foreach ($items as $item) {
    variable_del($item);
  }
}
